### ISSUE TITLE
Video is repeated

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/iteration_lecture_review#1]
This video is repeated in An Intro to Arrays... [Iteration Review](https://learn.co/tracks/web-development-with-ruby-on-rails/ruby/an-intro-to-arrays-iteration/iteration-review) and Looping [Iteration Lecture Review](https://learn.co/tracks/web-development-with-ruby-on-rails/ruby/looping/iteration-lecture-review)

**Comment by sammarcus** [comment]
@kvignali is this the reason why it discusses [my_each](https://github.com/learn-co-students/my-each-000) and `yield`ing before it was introduced to the student? If not I can open a new issue as a content concern.

**Comment by kvignali** [comment]
@sammarcus I'm not sure, I think someone closer to the curriculum would be better suited to answer that.

**Comment by sammarcus** [comment]
@kvignali No problem, I opened a [new issue](https://github.com/learn-co-curriculum/iteration_lecture_review/issues/2).

**Comment by AnnJohn** [comment]
Closing issue
