### ISSUE TITLE
Content concern: yield

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/iteration_lecture_review#2]
The video discusses [my_each](https://github.com/learn-co-curriculum/my-each) and `yield`ing far before they have been introduced to the user. Would it make sense to wait until the [my_each](hhttps://github.com/learn-co-curriculum/my-each) lab?

Also discussed in [this issue](https://github.com/learn-co-curriculum/iteration_lecture_review/issues/1).

**Comment by AnnJohn** [comment]
Closing this issue since it's referenced [#3](https://github.com/learn-co-curriculum/iteration_lecture_review/issues/3) too
