### ISSUE TITLE
Video talks about lots of stuff not yet covered

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/iteration_lecture_review#3]
like reading lines of a file into an array...

**Comment by AnnJohn** [comment]
Iceboxing the issue

**Comment by AnnJohn** [comment]
@SophieDeBenedetto @aviflombaum can we just remove this from the track? or place it further down?

**Comment by SophieDeBenedetto** [comment]
this is published in many precollege tracks. pre-college folks should decide to delete or not. I think it should def be deleted for the record.
